### ISSUE TITLE
Vector Tiles 

### ISSUE THREAD

**Issue by him29** [CUUATS/geojson-vt-py#2]
Here by this i am getting only one tile but what are the changes so that I can get all the vector tiles in the directory as  {z}/{x}/{y}..

**Comment by yomatters** [comment]
This is a direct port of [JS GeoJSON-VT](https://github.com/mapbox/geojson-vt), so the API is exactly the same. In order to get multiple tiles, you need to call the `getTile` method repeatedly with every z, x, and y combination you need. Please see the tests for examples of how to do this.

**Comment by him29** [comment]
Hello,
I am not to be able to store all the vector tiles into different
directories or folders like {z}/{x}/{y}..
Are they automatically generated by code ? if so then how?

**Comment by yomatters** [comment]
Like the JavaScript version, this module doesn't handle PBF encoding or filesystem operations. If you need those, you're probably better off using a tool like ogr2ogr (see the [MVT driver](https://www.gdal.org/drv_mvt.html)).
