### ISSUE TITLE
vector tile

### ISSUE THREAD

**Issue by him29** [CUUATS/geojson-vt-py#3]
thank you for this but for iteration of getTile(z,x,y) I have to pass values of z,x,y so how i get these values ? 
and I want vector tile output should be in directories as mentioned {z}/{x}/{y}...

**Comment by yomatters** [comment]
This module doesn't provide that functionality. To generate xyz values, you need to use something like [mercantile](https://github.com/mapbox/mercantile).

**Comment by him29** [comment]
I have one geojson file and I want to convert it into all geojson vector
tile and output should be stored in {z}/{x}/{y} directory.
So how to do it ? Is it possible to do it by this ?
